services:
  postgres:
    image: bitnami/postgresql:17
    container_name: postgres-gympass-api
    restart: unless-stopped
    environment:
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_DATABASE: gympassapi
    ports:
      - 5432:5432
    # volumes:
    #   - ./docker/postgres_data:/bitnami/postgresql
    networks:
      - solid-network
    expose:
      - 5432

networks:
  solid-network:
    driver: bridge